variables:
  # disable the Gradle daemon for Continuous Integration servers
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - publish

.buildtemplate: &builddefinition
  stage: build
  script:
    # create the executables for distribution
    - ./gradlew --build-cache assembleDist --info
    - mkdir bin
    - cp cli/build/libs/*.jar bin/
    - cp cli/build/distributions/*.zip bin/
    # create checksum file to make sure we're distributing the right thing
    - cd bin
    - md5sum *.{jar,zip} > checksums.txt
  artifacts:
    name: "$CI_COMMIT_REF_NAME-snapshot"
    paths:
      - bin
    expire_in: 1 week
  cache:
    key: "$CI_COMMIT_REF_NAME-$JAVA_VERSION"
    policy: push
    paths:
      - build
      - api/build
      - core/build
      - cli/build
      - .gradle

build:linux:jdk8:
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk8-latest
  <<: *builddefinition

build:linux:jdk11:
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk11-latest
  <<: *builddefinition

.testtemplate: &testdefinition
  stage: test
  script:
    - ./gradlew test
    - ./gradlew detekt
  cache:
    key: "$CI_COMMIT_REF_NAME-$JAVA_VERSION"
    policy: pull
    paths:
      - build
      - api/build
      - core/build
      - cli/build
      - .gradle

test:dependencies:
  stage: test
  needs: ["build:linux:jdk8"]
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk8-latest
  script:
    - ./gradlew dependencyUpdates

test:spotless:
  stage: test
  needs: ["build:linux:jdk8"]
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk8-latest
  script:
    - ./gradlew spotlessCheck

test:linux:jdk8:
  needs: ["build:linux:jdk8"]
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk8-latest
  <<: *testdefinition

test:linux:jdk11:
  needs: ["build:linux:jdk11"]
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk11-latest
  <<: *testdefinition

publish:gitlab:
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk8-latest
  stage: publish
  script:
    - ./gradlew publishGitLabPublicationToMavenRepository -PjobToken=$CI_JOB_TOKEN -Prelease=true
  only:
    refs:
      - tags
      - master

.ctantemplate: &ctandefinition
  stage: publish
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends zip
    - ./gradlew -Prelease=$PRELEASE assembleCTAN --info
    - cp build/*.zip ./
  artifacts:
    name: "$CI_COMMIT_REF_NAME-ctan"
    paths:
      - ./*.zip
      - docs/*.pdf
publish:snapshot_tdszip:
  variables:
    PRELEASE: "false"
  <<: *ctandefinition
  except:
    refs:
      - tags
      - master
publish:tdszip:
  variables:
    PRELEASE: "true"
  <<: *ctandefinition
  only:
    refs:
      - tags
      - master
